### ISSUE TITLE
Tasklists

### ISSUE THREAD

**Issue by rezrah** [rezrah/social-image-generator#9]
```[tasklist]
### Phase 1: Transition from PoC to MVP
- [ ] Migrate project + repo into GitHub org
- [ ] Replace OAuth app authentication with GitHub authorisation
- [ ] Move Primer Figma API to separate project (💰) 
- [ ] Speed up Azure infrastructure (💰)
```

```[tasklist]
### Phase 2: Release template for {name of commercial activity / event}
- [ ] Refine template for [social banner](https://rezrah.github.io/social-image-generator/create/social-banner)
- [ ] Use OpenAI CLIP to generate alt text after image creation  (💰)
```
